### ISSUE TITLE
Latest GIT version of zabbix-cli with Zabbix 3.4 gives an error 412, pre-condition failed

### ISSUE THREAD

**Issue by RobertLHarris** [usit-gd/zabbix-cli#76] opened 2018-10-15 19:17 UTC
Ubuntu 18.04 trying to connect to a CentOS system running Zabbix 3.4.  I run "zabbix-cli".  It asks for username/password then gives me : 

[ERROR]: 412 Client Error: Precondition Failed for url: https://zabbix-server/api_jsonrpc.php

**Comment by paalbra** [comment] 2019-01-16 13:22
@RobertLHarris Is this still a problem for you?

If so:
What authentication mechanism are you using?

Is your webserver set up in any special way?

**Comment by paalbra** [comment] 2019-01-30 13:31
I'm not able to reproduce this issue and I'm not sure what version of zabbix-cli/specific commit you were using.

This might occur if some erroneous HTTP headers are sent.

I'm closing this issue for now. Feel free to reopen with some more details if you're still experiencing this issue.

**Closed by paalbra** 2019-01-30 13:31 UTC
Labels: waiting for feedback
