### ISSUE TITLE
Authentication error with Zabbix 4.0

### ISSUE THREAD

**Issue by Thulium-Drake** [usit-gd/zabbix-cli#80] opened 2018-11-30 08:50 UTC
Hi!

This morning I upgraded my Zabbix server to 4.0 after coming from 3.4. My setup is as follows:

* HTTP Basic authentication is enabled on Apache
* zabbix-cli is an Zabbix Super Admin
* I configured zabbix-cli with the following commands:
```
zabbix-cli-init -z https://USERNAME:PASSWORD@zabbix.example.com
echo USERNAME::PASSWORD > ~/.zabbix-cli_auth
```

This worked like a charm on 3.4, however when I try to run zabbix-cli on 4.0 i get the following error:
```
[ERROR]:  (u'Error -32602: Invalid params.: Login name or password is incorrect.', -32602)
```

Removing the USERNAME:PASSWORD part from the URL results in (which is expected, due to basic auth being active)
```
[ERROR]:  401 Client Error: Unauthorized for url: https://zabbix-test.airbusds.nl/api_jsonrpc.php
```

Logging in via my browser using the same account works, so it has to be something with the handling of the credentials towards the API. Or the configuration borked somewhere in the upgrade.

I did read the notes on https://www.zabbix.com/documentation/4.0/manual/installation/upgrade_notes_400 and re-configured Zabbix to HTTP basic auth again (and use the HTTP authentication by default).

P.S. I am aware that the original configuration I used (encoding credentials in the URL for basic auth and then signing in on the API using the same credentials) is a hack to work around the lack of HTTP_BASIC auth support :-)

**Comment by Thulium-Drake** [comment] 2018-11-30 09:03
I found a workaround, NOT a solution to this issue!

It appears that in contrary to the directions of the upgrade notes, which will tell you to delete all the Zabbix passwords in the database (note, before I removed the passwords from the database as per the directions it was already broken), the user you wish the use for zabbix-cli MUST have a password.

When setting the same password you use in Apache for the basic authentication on the useraccount in Zabbix, it will work again.

But I think a proper solution to this issue would be the addition of HTTP_BASIC authentication.

Cheers! :-)

**Comment by paalbra** [comment] 2019-01-16 12:10
I haven't been able/had the time to reproduce this error (since we're using other authentication mechanisms that work with Zabbix 4).

Do you think you're able to provide a example configuration for the docker containers that displays this problem?

**Comment by paalbra** [comment] 2019-02-12 09:46
As you can see in [ZBX-15569](https://support.zabbix.com/browse/ZBX-15569) internal username and password is required in Zabbix 4.0. Basic auth only is therefore something zabbix-cli can't support.

The [upgrade notes](https://www.zabbix.com/documentation/4.0/manual/installation/upgrade_notes_400) has also been updated with:
`HTTP basic-authentication specific code was removed from API, therefore the password field is now mandatory for the API user.login action.`

I'm closing this issue.

**Closed by paalbra** 2019-02-12 09:46 UTC
Labels: invalid, waiting for feedback
