### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by leweafan** [usit-gd/zabbix-cli#68] opened 2018-05-07 15:22 UTC
I haven't been able to export output in a non-interactive mode. Seems like it possible only if I create authentication file.

**Comment by paalbra** [comment] 2019-01-15 12:58
Could you elaborate?

Reproduction steps?

**Comment by paalbra** [comment] 2019-05-03 11:49
I'm closing this due to lacking feedback

**Closed by paalbra** 2019-05-03 11:49 UTC
Labels: waiting for feedback
