### ISSUE TITLE
Zabbix-cli chmod issue causing to not read .zabbix-cli_auth

### ISSUE THREAD

**Issue by breisig** [usit-gd/zabbix-cli#81] opened 2018-12-04 23:41 UTC
I have installed Zabbix 4.0.2 (on CentOS 7.6) and downloaded the latest zabbix-cli from master and when I try to setup an ~/.zabbix-cli_auth file in my home directory, it complains with 

[ERROR]:chmod() takes no keyword arguments
[ERROR]: Username or password is empty

I have tried the following

echo "admin::mypassword" > $HOME/.zabbix-cli_auth
chmod 400 $HOME/.zabbix-cli_auth
zabbix-cli

[ERROR]:chmod() takes no keyword arguments
[ERROR]: Username or password is empty

However, if I set the environment variables ZABBIX_USERNAME and ZABBIX_PASSWORD with the same login and password, zabbix-cli works without any issues.

**Comment by paalbra** [comment] 2018-12-05 11:36
Yes, this issue was introduced in a commit mentioned here #59. This issue is still present in the current master. Right now you will have to use an older commit or give python3 a try.

You should be aware that zabbix-cli isn't tested with Zabbix 4 yet. There will probably be a major rewrite, hopefully, early next year that makes sure zabbix-cli is fully compatible with Zabbix 4.

Thanks for the extra info, but I'm closing this issue since the problem is already mentioned in #59

**Closed by paalbra** 2018-12-05 11:36 UTC
